"""
Entity protocols for MyTower game.
Defines interfaces for game entities to avoid circular imports and improve testability.
"""

from __future__ import annotations
from typing import TYPE_CHECKING, Protocol, List, Sequence
from mytower.game.core.units import Blocks, Velocity, Time
from mytower.game.core.types import HorizontalDirection, PersonState, ElevatorState, VerticalDirection

if TYPE_CHECKING:
    from mytower.game.entities.building import Building
    from mytower.game.entities.elevator_bank import ElevatorBank
    from mytower.game.entities.floor import Floor
    from mytower.game.entities.elevator import Elevator


class PersonProtocol(Protocol):
    """Protocol defining the interface for Person entities"""
    
    @property
    def current_floor_num(self) -> int: ...
    
    @property
    def current_floor_float(self) -> Blocks: ...

    @property
    def destination_floor_num(self) -> int: ...
    
    @property
    def current_block_float(self) -> Blocks: ...
    
    @property
    def current_floor(self) -> Floor | None: ...
    
    @property
    def destination_block_num(self) -> Blocks: ...
    
    @property
    def person_id(self) -> str: ...
    
    @property
    def state(self) -> PersonState: ...
    
    @property
    def direction(self) -> HorizontalDirection: ...
    
    @direction.setter
    def direction(self, value: HorizontalDirection) -> None: ...
    
    @property
    def max_velocity(self) -> Velocity: ...
    
    @property
    def building(self) -> Building: ...
    
    @property
    def waiting_time(self) -> Time: ...
    
    @property
    def mad_fraction(self) -> float: ...
    
    @property
    def draw_color(self) -> tuple[int, int, int]: ...

    def set_destination(self, dest_floor_num: int, dest_block_num: Blocks) -> None: ...
    
    def find_nearest_elevator_bank(self) -> None | ElevatorBank: ...
    
    def board_elevator(self, elevator: Elevator) -> None: ...
    
    def disembark_elevator(self) -> None: ...

    def update(self, dt: Time) -> None: ...

    def update_idle(self, dt: Time) -> None: ...

    def update_walking(self, dt: Time) -> None: ...

    def testing_set_dest_floor_num(self, dest_floor: int) -> None: ...


class ElevatorProtocol(Protocol):
    """Protocol defining the interface for Elevator entities"""
    
    @property
    def elevator_id(self) -> str: ...
    
    @property
    def state(self) -> ElevatorState: ...
    
    @property
    def current_floor_int(self) -> int: ...
    
    @property
    def fractional_floor(self) -> Blocks: ...
    
    @property
    def current_block_float(self) -> Blocks: ...
    
    @property
    def destination_floor(self) -> int: ...
    
    @property
    def max_velocity(self) -> Velocity: ...
    
    @property
    def min_floor(self) -> int: ...
    
    @property
    def max_floor(self) -> int: ...
    
    @property
    def passenger_count(self) -> int: ...
    
    @property
    def max_capacity(self) -> int: ...
    
    @property
    def avail_capacity(self) -> int: ...
    
    @property
    def door_open(self) -> bool: ...
    
    @door_open.setter
    def door_open(self, value: bool) -> None: ...
    
    @property
    def motion_direction(self) -> VerticalDirection: ...
    
    @property
    def nominal_direction(self) -> VerticalDirection: ...
    
    @property
    def parent_elevator_bank(self) -> ElevatorBankProtocol: ...
    
    @property
    def is_empty(self) -> bool: ...
    
    @property
    def idle_time(self) -> Time: ...
    
    @idle_time.setter
    def idle_time(self, value: Time) -> None: ...
    
    @property
    def idle_wait_timeout(self) -> Time: ...
    
    def set_destination_floor(self, dest_floor: int) -> None: ...
    
    def update(self, dt: Time) -> None: ...
    
    def get_passenger_destinations_in_direction(self, floor: int, direction: VerticalDirection) -> List[int]: ...
    
    def request_load_passengers(self, direction: VerticalDirection) -> None: ...
    
    def passengers_who_want_off(self) -> List[PersonProtocol]: ...


class ElevatorTestingProtocol(Protocol):
    """Testing-only protocol for Elevator - provides internal state access for unit tests"""
    
    def testing_set_state(self, state: ElevatorState) -> None: ...
    
    def testing_set_motion_direction(self, direction: VerticalDirection) -> None: ...
    
    def testing_set_nominal_direction(self, direction: VerticalDirection) -> None: ...
    
    def testing_set_current_floor(self, floor: Blocks) -> None: ...
    
    def testing_set_passengers(self, passengers: Sequence[PersonProtocol]) -> None: ...
    
    def testing_get_passengers(self) -> List[PersonProtocol]: ...


class FloorProtocol(Protocol):
    """Protocol defining the interface for Floor entities"""
    
    @property
    def floor_num(self) -> int: ...
    
    @property
    def width(self) -> Blocks: ...
    
    @property
    def height(self) -> Blocks: ...
    
    @property
    def number_of_people(self) -> int: ...
    
    def add_person(self, person: PersonProtocol) -> None: ...
    
    def remove_person(self, person_id: str) -> None: ...


class ElevatorBankProtocol(Protocol):
    """Protocol defining the interface for ElevatorBank entities"""
    
    @property
    def elevator_bank_id(self) -> str: ...
    
    @property
    def horizontal_block(self) -> Blocks: ...
    
    @property
    def min_floor(self) -> int: ...
    
    @property
    def max_floor(self) -> int: ...
    
    @property
    def elevators(self) -> List[Elevator]: ...
    
    def get_waiting_block(self) -> Blocks: ...
    
    def add_waiting_passenger(self, passenger: PersonProtocol) -> None: ...
    
    def request_elevator(self, floor: int, direction: VerticalDirection) -> None: ...
    
    def try_dequeue_waiting_passenger(self, floor: int, direction: VerticalDirection) -> PersonProtocol | None: ...
